// <auto-generated />
using System;
using AdminDashboard.TransportDBContext;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AdminDashboard.Migrations
{
    [DbContext(typeof(Db27524Context))]
    [Migration("20251019104145_InitialCreateWithChuyenXeImage")]
    partial class InitialCreateWithChuyenXeImage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AdminDashboard.Models.BaiViet", b =>
                {
                    b.Property<string>("Id")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AdminId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDang")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TieuDe")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("AdminId");

                    b.ToTable("BaiViet");
                });

            modelBuilder.Entity("AdminDashboard.Models.ChuyenXe", b =>
                {
                    b.Property<string>("ChuyenId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<TimeSpan>("GioDenDuKien")
                        .HasColumnType("time");

                    b.Property<TimeSpan>("GioDi")
                        .HasColumnType("time");

                    b.Property<string>("LoTrinhId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDi")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiXeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.Property<string>("XeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("ChuyenId");

                    b.HasIndex("LoTrinhId");

                    b.HasIndex("TaiXeId");

                    b.HasIndex("XeId");

                    b.ToTable("ChuyenXe");
                });

            modelBuilder.Entity("AdminDashboard.Models.ChuyenXeImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<string>("ChuyenId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("datetime2")
                        .HasDefaultValueSql("GETDATE()");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.HasKey("ImageId");

                    b.HasIndex("ChuyenId");

                    b.ToTable("ChuyenXeImage");
                });

            modelBuilder.Entity("AdminDashboard.Models.DonHang", b =>
                {
                    b.Property<string>("DonHangId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ChuyenId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("IDKhachHang")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime>("NgayDat")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("ThoiGianHetHan")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("TongTien")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("TrangThaiThanhToan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("DonHangId");

                    b.HasIndex("ChuyenId");

                    b.HasIndex("IDKhachHang");

                    b.ToTable("DonHang");
                });

            modelBuilder.Entity("AdminDashboard.Models.Ghe", b =>
                {
                    b.Property<string>("GheID")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("SoGhe")
                        .IsRequired()
                        .HasMaxLength(6)
                        .HasColumnType("nvarchar(6)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("XeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("GheID");

                    b.HasIndex("XeId");

                    b.ToTable("Ghe");
                });

            modelBuilder.Entity("AdminDashboard.Models.LoTrinh", b =>
                {
                    b.Property<string>("LoTrinhId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal?>("GiaVeCoDinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TramDi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TramToi")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("LoTrinhId");

                    b.HasIndex("TramDi");

                    b.HasIndex("TramToi");

                    b.ToTable("LoTrinh");
                });

            modelBuilder.Entity("AdminDashboard.Models.LoaiXe", b =>
                {
                    b.Property<string>("LoaiXeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenLoaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("LoaiXeId");

                    b.ToTable("LoaiXe");
                });

            modelBuilder.Entity("AdminDashboard.Models.NguoiDung", b =>
                {
                    b.Property<string>("UserId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MatKhau")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("NgaySinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoDienThoai")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("UserId");

                    b.ToTable("NguoiDung");
                });

            modelBuilder.Entity("AdminDashboard.Models.TaiXe", b =>
                {
                    b.Property<int>("TaiXeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TaiXeId"));

                    b.Property<string>("AdminId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("BangLaiXe")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("NgayVaoLam")
                        .HasColumnType("datetime2");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("TaiXeId");

                    b.HasIndex("AdminId");

                    b.HasIndex("UserId");

                    b.ToTable("TaiXe", (string)null);
                });

            modelBuilder.Entity("AdminDashboard.Models.Tram", b =>
                {
                    b.Property<string>("IdTram")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DiaChiTram")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Huyen")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TenTram")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Tinh")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Xa")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdTram");

                    b.ToTable("Tram");
                });

            modelBuilder.Entity("AdminDashboard.Models.UserRole", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRole");
                });

            modelBuilder.Entity("AdminDashboard.Models.VaiTro", b =>
                {
                    b.Property<string>("RoleId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TenVaiTro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("RoleId");

                    b.ToTable("VaiTro");
                });

            modelBuilder.Entity("AdminDashboard.Models.Ve", b =>
                {
                    b.Property<string>("VeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("DonHangId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("GheID")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<decimal>("Gia")
                        .HasColumnType("numeric(10,2)");

                    b.HasKey("VeId");

                    b.HasIndex("DonHangId");

                    b.HasIndex("GheID");

                    b.ToTable("Ve");
                });

            modelBuilder.Entity("AdminDashboard.Models.Xe", b =>
                {
                    b.Property<string>("XeId")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("BienSoXe")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("LoaiXeId")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("XeId");

                    b.HasIndex("LoaiXeId");

                    b.ToTable("Xe");
                });

            modelBuilder.Entity("AdminDashboard.Models.BaiViet", b =>
                {
                    b.HasOne("AdminDashboard.Models.NguoiDung", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId");

                    b.Navigation("Admin");
                });

            modelBuilder.Entity("AdminDashboard.Models.ChuyenXe", b =>
                {
                    b.HasOne("AdminDashboard.Models.LoTrinh", "LoTrinh")
                        .WithMany()
                        .HasForeignKey("LoTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.NguoiDung", "TaiXe")
                        .WithMany()
                        .HasForeignKey("TaiXeId");

                    b.HasOne("AdminDashboard.Models.Xe", "Xe")
                        .WithMany()
                        .HasForeignKey("XeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoTrinh");

                    b.Navigation("TaiXe");

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("AdminDashboard.Models.ChuyenXeImage", b =>
                {
                    b.HasOne("AdminDashboard.Models.ChuyenXe", "ChuyenXe")
                        .WithMany("Images")
                        .HasForeignKey("ChuyenId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenXe");
                });

            modelBuilder.Entity("AdminDashboard.Models.DonHang", b =>
                {
                    b.HasOne("AdminDashboard.Models.ChuyenXe", "ChuyenXe")
                        .WithMany()
                        .HasForeignKey("ChuyenId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.NguoiDung", "nguoiDung")
                        .WithMany()
                        .HasForeignKey("IDKhachHang")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChuyenXe");

                    b.Navigation("nguoiDung");
                });

            modelBuilder.Entity("AdminDashboard.Models.Ghe", b =>
                {
                    b.HasOne("AdminDashboard.Models.Xe", "Xe")
                        .WithMany("DanhSachGhe")
                        .HasForeignKey("XeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Xe");
                });

            modelBuilder.Entity("AdminDashboard.Models.LoTrinh", b =>
                {
                    b.HasOne("AdminDashboard.Models.Tram", "TramDiNavigation")
                        .WithMany()
                        .HasForeignKey("TramDi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.Tram", "TramToiNavigation")
                        .WithMany()
                        .HasForeignKey("TramToi")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("TramDiNavigation");

                    b.Navigation("TramToiNavigation");
                });

            modelBuilder.Entity("AdminDashboard.Models.TaiXe", b =>
                {
                    b.HasOne("AdminDashboard.Models.NguoiDung", "Admin")
                        .WithMany()
                        .HasForeignKey("AdminId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.NguoiDung", "NguoiDung")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Admin");

                    b.Navigation("NguoiDung");
                });

            modelBuilder.Entity("AdminDashboard.Models.UserRole", b =>
                {
                    b.HasOne("AdminDashboard.Models.VaiTro", "VaiTro")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.NguoiDung", "NguoiDung")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NguoiDung");

                    b.Navigation("VaiTro");
                });

            modelBuilder.Entity("AdminDashboard.Models.Ve", b =>
                {
                    b.HasOne("AdminDashboard.Models.DonHang", "DonHang")
                        .WithMany()
                        .HasForeignKey("DonHangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AdminDashboard.Models.Ghe", "Ghe")
                        .WithMany()
                        .HasForeignKey("GheID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("DonHang");

                    b.Navigation("Ghe");
                });

            modelBuilder.Entity("AdminDashboard.Models.Xe", b =>
                {
                    b.HasOne("AdminDashboard.Models.LoaiXe", "LoaiXe")
                        .WithMany()
                        .HasForeignKey("LoaiXeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("LoaiXe");
                });

            modelBuilder.Entity("AdminDashboard.Models.ChuyenXe", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("AdminDashboard.Models.NguoiDung", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AdminDashboard.Models.VaiTro", b =>
                {
                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("AdminDashboard.Models.Xe", b =>
                {
                    b.Navigation("DanhSachGhe");
                });
#pragma warning restore 612, 618
        }
    }
}
